# Generated by Django 5.1.5 on 2025-02-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="is_special",
            field=models.BooleanField(default=False, verbose_name="برای کاربران ویژه"),
        ),
    ]
