# Generated by Django 5.1.4 on 2025-01-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='built_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
