# Generated by Django 5.1.5 on 2025-02-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_property_is_special"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.BigIntegerField(verbose_name="قیمت"),
        ),
    ]
