# Generated by Django 5.1.5 on 2025-02-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_alter_property_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="post_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="تاریخ پست"),
        ),
    ]
