# Generated by Django 5.1.5 on 2025-02-12 17:17

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_alter_property_post_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="type",
        ),
        migrations.AddField(
            model_name="property",
            name="equipment",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("pa", "پارکینگ"),
                    ("wh", "انباری"),
                    ("cb", "کمد دیواری"),
                    ("pn", "نقاشی"),
                    ("tr", "تراس"),
                    ("vd", "آیفون تصویری"),
                    ("el", "آسانسور"),
                    ("gb", "درب برقی"),
                    ("wc", "سرویس فرنگی"),
                    ("wp", "کاغذ دیواری"),
                    ("pk", "پکیج"),
                    ("ac", "کولر گازی"),
                    ("sh", "شوفاژ"),
                    ("lb", "لابی"),
                    ("ds", "درب ضد سرقت"),
                    ("cc", "دوربین مداربسته"),
                    ("pnk", "پانل\u200cکوبی"),
                    ("st", "گاز رومیزی"),
                    ("hd", "هود"),
                    ("mb", "حمام مستر"),
                    ("rd", "رادیاتور"),
                    ("rg", "روف گاردن"),
                    ("gm", "سالن ورزش"),
                ],
                max_length=69,
                null=True,
            ),
        ),
    ]
