# Generated by Django 5.1.5 on 2025-02-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_remove_property_type_property_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[("آپارتمان", "Apartment"), ("خانه", "House")],
                default="آپارتمان",
                max_length=50,
                verbose_name="نوع",
            ),
        ),
    ]
