# Generated by Django 5.1.5 on 2025-02-13 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_property_property_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="equipment",
        ),
    ]
