# Generated by Django 5.1.4 on 2025-01-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='slug',
        ),
    ]
