# Generated by Django 5.1.5 on 2025-02-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0009_alter_property_equipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="equipment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pa", "پارکینگ"),
                    ("wh", "انباری"),
                    ("cb", "کمد دیواری"),
                    ("pn", "نقاشی"),
                    ("tr", "تراس"),
                    ("vd", "آیفون تصویری"),
                    ("el", "آسانسور"),
                    ("gb", "درب برقی"),
                    ("wc", "سرویس فرنگی"),
                    ("wp", "کاغذ دیواری"),
                    ("pk", "پکیج"),
                    ("ac", "کولر گازی"),
                    ("sh", "شوفاژ"),
                    ("lb", "لابی"),
                    ("ds", "درب ضد سرقت"),
                    ("cc", "دوربین مداربسته"),
                    ("pnk", "پانل\u200cکوبی"),
                    ("st", "گاز رومیزی"),
                    ("hd", "هود"),
                    ("mb", "حمام مستر"),
                    ("rd", "رادیاتور"),
                    ("rg", "روف گاردن"),
                    ("gm", "سالن ورزش"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
