# Generated by Django 5.1.5 on 2025-02-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_alter_property_equipment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("icon", models.FileField(blank=True, null=True, upload_to="icons/")),
            ],
        ),
        migrations.RemoveField(
            model_name="property",
            name="equipment",
        ),
        migrations.AddField(
            model_name="property",
            name="equipment",
            field=models.ManyToManyField(
                blank=True, null=True, to="properties.equipment"
            ),
        ),
    ]
