# Generated by Django 5.1.4 on 2025-01-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
