# Generated by Django 5.1.4 on 2025-01-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_alter_property_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='area',
            new_name='lot_area',
        ),
        migrations.AddField(
            model_name='property',
            name='elevator',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floors',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='warehouse',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
