# Generated by Django 5.1.4 on 2025-01-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_category_remove_property_type_property_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.BooleanField(null=True),
        ),
    ]
