# Generated by Django 5.1.4 on 2025-01-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_alter_property_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('آپارتمان', 'Apartment'), ('خانه', 'House')], default='آپارتمان', max_length=50),
        ),
    ]
