# Generated by Django 5.1.4 on 2025-01-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(),
        ),
    ]
