# Generated by Django 5.1.4 on 2025-01-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_alter_category_slug_alter_property_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
