# Generated by Django 5.1.4 on 2025-01-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_property_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
