# Generated by Django 5.1.4 on 2025-01-22 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_alter_property_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathroom',
            field=models.IntegerField(verbose_name='دستشویی'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom',
            field=models.IntegerField(verbose_name='اتاق خواب'),
        ),
        migrations.AlterField(
            model_name='property',
            name='built_year',
            field=models.IntegerField(null=True, verbose_name='سال ساخت'),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='property',
            name='elevator',
            field=models.BooleanField(default=False, null=True, verbose_name='آسانسور'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_area',
            field=models.IntegerField(null=True, verbose_name='متراژ سازه'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floors',
            field=models.IntegerField(null=True, verbose_name='تعداد طبقات'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='وضعیت تایید'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=150, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='property',
            name='lot_area',
            field=models.IntegerField(verbose_name='متراژ کل'),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.BooleanField(null=True, verbose_name='پارکینگ'),
        ),
        migrations.AlterField(
            model_name='property',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ پست'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='پیوند'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(max_length=100, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('آپارتمان', 'Apartment'), ('خانه', 'House')], default='آپارتمان', max_length=50, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='property',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='property',
            name='warehouse',
            field=models.BooleanField(default=False, null=True, verbose_name='انباری'),
        ),
    ]
