# Generated by Django 5.1.4 on 2025-01-22 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_alter_property_bathroom_alter_property_bedroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='slug',
        ),
    ]
