# Generated by Django 5.1.4 on 2025-01-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_remove_property_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='post_date',
            field=models.DateTimeField(null=True, verbose_name='تاریخ پست'),
        ),
    ]
